version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1
      POSTGRES_DB: purchases_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
